version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=mysql

  web:
    build:
      context: ./test_travis
      dockerfile: Dockerfile
    entrypoint: /code/entrypoint.sh
    volumes:
      - ./test_travis/:/code
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    ports:
      - "8001:80"
    volumes:
      - ./nginx/conf/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/tmp:/tmp/
      - ./test_travis/static:/usr/share/nginx/html/static
      - ./test_travis/media:/usr/share/nginx/html/media
    depends_on:
      - web
